# Generated by Django 4.2.15 on 2025-09-27 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='missionassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mission',
            name='frequency',
            field=models.CharField(choices=[('adhoc', 'Ad-hoc'), ('daily', 'Daily')], default='adhoc', max_length=20),
        ),
        migrations.AddField(
            model_name='mission',
            name='reward_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='reward_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='mission',
            name='reward_type',
            field=models.CharField(choices=[('currency', 'Currency'), ('stamp', 'Stamp'), ('badge', 'Badge')], default='currency', max_length=20),
        ),
        migrations.AddField(
            model_name='missionassignment',
            name='date_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missionassignment',
            name='reward_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='missionassignment',
            unique_together={('user', 'mission', 'date_for')},
        ),
        migrations.CreateModel(
            name='MissionRewardLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_type', models.CharField(choices=[('currency', 'Currency'), ('stamp', 'Stamp'), ('badge', 'Badge')], max_length=20)),
                ('reward_code', models.CharField(blank=True, max_length=80)),
                ('reward_amount', models.PositiveIntegerField(default=0)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_log', to='missions.missionassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
