# Generated by Django 4.2.15 on 2025-09-24 14:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('body', models.TextField(blank=True)),
                ('post_type', models.CharField(choices=[('review', '후기'), ('doodle', '낙서')], default='review', max_length=20)),
                ('visibility', models.CharField(choices=[('private', '비공개'), ('friends', '친구공개'), ('public', '전체공개')], default='private', max_length=20)),
                ('status', models.CharField(choices=[('draft', '작성중'), ('published', '게시됨'), ('flagged', '검토 필요'), ('archived', '보관')], default='published', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('geofence', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, help_text='낙서 24시간 만료용', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.tag')),
            ],
        ),
    ]
