# Generated by Django 4.2.15 on 2025-09-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postmessage_postcomment_postlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostMessage',
        ),
    ]
