# Generated by Django 4.2.15 on 2025-09-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_delete_postmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='게시 후 24시간 뒤 자동 만료', null=True),
        ),
    ]
