name: kakao_map_sdk
description: "A Flutter plugin that provides a native platform-based Kakao Map(Korean Map Service)."
version: 1.1.4
repository: https://github.com/gunyu1019/flutter_kakao_maps
issue_tracker: https://github.com/gunyu1019/flutter_kakao_maps/issues?q=is%3Aissue%20is%3Aopen

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  uuid: ^4.5.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: kr.yhs.flutter_kakao_maps
        pluginClass: FlutterKakaoMapsPlugin
      ios:
        pluginClass: FlutterKakaoMapsPlugin
      web:
        pluginClass: KakaoMapWebPlugin
        fileName: web/kakao_map_sdk_web.dart