# Generated by Django 4.2.15 on 2025-09-24 14:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('context_hash', models.CharField(db_index=True, max_length=64)),
                ('inputs', models.JSONField(blank=True, default=dict, help_text='요청시 제약 조건 기록')),
                ('duration_min', models.PositiveIntegerField(default=90)),
                ('budget_min', models.PositiveIntegerField(default=0)),
                ('budget_max', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(choices=[('walk', '도보'), ('transit', '대중교통'), ('bike', '자전거'), ('drive', '자가용')], default='walk', max_length=16)),
                ('freshness_score', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('planned_stay_min', models.PositiveIntegerField(default=30)),
                ('transition_mode', models.CharField(choices=[('walk', '도보'), ('transit', '대중교통'), ('bike', '자전거'), ('drive', '자가용')], default='walk', max_length=16)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_nodes', to='places.place')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
