# Generated by Django 4.2.15 on 2025-09-24 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tripnode',
            unique_together={('trip', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['context_hash'], name='trips_trip_context_59f3db_idx'),
        ),
    ]
