# Generated by Django 4.2.15 on 2025-09-26 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0002_favoriteplace'),
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hero_image_url', models.URLField(blank=True)),
                ('duration_min', models.PositiveIntegerField(default=90)),
                ('budget_min', models.PositiveIntegerField(default=0)),
                ('budget_max', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(choices=[('walk', '도보'), ('transit', '대중교통'), ('bike', '자전거'), ('drive', '자가용')], default='walk', max_length=16)),
                ('mood_tags', models.JSONField(blank=True, default=list)),
                ('origin', models.CharField(choices=[('editor', '에디터'), ('ai', 'AI')], default='editor', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trip_templates', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='trip_templates', to='places.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripTemplateNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('stay_min', models.PositiveIntegerField(default=30)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_nodes', to='places.place')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='trips.triptemplate')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('template', 'sequence')},
            },
        ),
        migrations.AddIndex(
            model_name='triptemplate',
            index=models.Index(fields=['is_published', 'created_at'], name='trips_tript_is_publ_7399f6_idx'),
        ),
    ]
