# Generated by Django 4.2.15 on 2025-09-24 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('channel', models.CharField(choices=[('push', '푸시'), ('email', '이메일'), ('inapp', '앱 내')], default='push', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=500)),
                ('auth_key', models.CharField(max_length=120)),
                ('p256dh', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
