# Generated by Django 4.2.15 on 2025-09-24 14:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('external_ref', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('location', models.JSONField(blank=True, default=dict, help_text='GeoJSON Point representation')),
                ('cost_band', models.CharField(blank=True, max_length=30)),
                ('stay_min', models.PositiveIntegerField(default=60)),
                ('hours', models.JSONField(blank=True, default=dict)),
                ('mood_scores', models.JSONField(blank=True, default=dict)),
                ('congestion_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('category', '카테고리'), ('mood', '분위기'), ('time', '시간대'), ('congestion', '혼잡도'), ('budget', '예산'), ('custom', '사용자 정의')], default='category', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='PlaceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.tag')),
            ],
            options={
                'unique_together': {('place', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(related_name='places', through='places.PlaceTag', to='places.tag'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['category'], name='places_plac_categor_0dcb38_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['district'], name='places_plac_distric_92a2f8_idx'),
        ),
    ]
