# Generated by Django 4.2.15 on 2025-09-24 14:56

from django.db import migrations, models
import django.utils.timezone
import lifelog.users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('nickname', models.CharField(blank=True, max_length=40)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.URLField(blank=True)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('time_budget_min', models.PositiveIntegerField(default=120, help_text='선호하는 체류 시간 예산(분)')),
                ('budget_band', models.CharField(blank=True, max_length=30)),
                ('mobility_mode', models.CharField(choices=[('walk', '도보'), ('transit', '대중교통'), ('bike', '자전거'), ('drive', '자가용')], default='walk', max_length=16)),
                ('privacy_level', models.CharField(choices=[('private', '비공개'), ('friends', '친구만'), ('public', '전체공개')], default='private', max_length=16)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('push_opt_in', models.BooleanField(default=True)),
                ('location_opt_in', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='users_user_email_6f2530_idx')],
            },
            managers=[
                ('objects', lifelog.users.models.UserManager()),
            ],
        ),
    ]
