# Generated by Django 4.2.15 on 2025-09-26 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_favoriteplace'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferredTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=120)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_by', to='places.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-priority', '-created_at'),
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
